### ISSUE TITLE
Outdated URL in notebook 03-Reading-and-writing-data-in-Azure-Databricks

### ISSUE THREAD

**Issue by barasztamas** [solliancenet/microsoft-learning-paths-databricks-notebooks#4]
In this [notebook](https://github.com/solliancenet/microsoft-learning-paths-databricks-notebooks/blob/master/data-engineering/DBC/03-Reading-and-writing-data-in-Azure-Databricks.dbc) the _Spark API Documentation - Latest_ [URL](https://spark.apache.org/docs/latest/api.html) is broken.
The correct url would be https://spark.apache.org/docs/latest/api/

**Comment by barasztamas** [comment]
thank you @joelhulen

**Comment by joelhulen** [comment]
Thank you!

**Comment by barasztamas** [comment]
@joelhulen same issue [here](https://github.com/solliancenet/microsoft-learning-paths-databricks-notebooks/blob/master/data-engineering/DBC/04-Working-With-Dataframes.dbc) in notebook _2.Use-common-dataframe-methods_
