### ISSUE TITLE
java.util.NoSuchElementException: com.databricks.training.azure.datasource

### ISSUE THREAD

**Issue by theguyoverthere** [solliancenet/microsoft-learning-paths-databricks-notebooks#5]
Executing the notebook 1.DateTime-Manipulation under 07-Dataframe-Advanced-Methods results in the error "
java.util.NoSuchElementException: com.databricks.training.azure.datasource" Apparently the configuration com.databricks.training.azure.datasource isn't get set up by the %run "./Includes/Classroom-Setup" notebook executed earlier.

I'm running the notebook on Databricks Community Edition.

**Comment by joelhulen** [comment]
I cannot reproduce this error on Azure Databricks. You are receiving the error because you're running Databricks Community Edition, which does not have the extra libraries and configurations used by Azure Databricks (PaaS service). Therefore, you cannot successfully run this notebook.

**Comment by theguyoverthere** [comment]
Thank you for looking into this. I believe this happened because the Community Edition uses AWS servers instead of Azure instances, however the notebook specifically references the Azure function getAzureDataSource().
